apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  labels:
    name: airflow-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
     name: result-app-pod
