apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  labels:
    app: airflow-pod-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
    name: airflow-pod
    app: airflow-pod-app
    labels:
      name: airflow-pod
      app: airflow-pod-app
    spec:
      containers:
      - name: airflow_container
        image: https://public.ecr.aws/w4n2x3q5/kube_project_ecr_repo:latest
        ports:
        - containerPort: 8080
